### ISSUE TITLE
Few Advise

### ISSUE THREAD

**Issue by manju-rn** [SMak06/IOT-home_automation#1]
Since you are starting new on the ESP8266, want to add few advice to make is simpler to work with. ESP8266 is not difficult or delicate as you have indicated in your report:
1. Use ESP-01 adapter (which contains a USB header), like the one below, it allows you to directly plug in the ESP 8266 and connect to PC via USB
https://www.amazon.com/ESP-01S-ESP8266-Wireless-Adapter-4-5-5-5V/dp/B07KF119YB/ref=sr_1_4?crid=275DBFTUZVB7A&keywords=esp-01+adapter&qid=1572190013&sprefix=ESP-01+Adapt%2Caps%2C396&sr=8-4

2. There are plenty of ESP Flasher progams - one such is ESP Flasher, developer by creator of ESPHome - it is super simple and stable unlike the program you are using
https://github.com/esphome/esphome-flasher/tree/master/esphomeflasher

3. ESP devices, if used in a standalone fashion are more like "Glorified" remote control. The real power of ESP devices come into affect when they are used in swarm and connected to a IoT hub, such as Home Assistant, OpenHab, etc.  You could develop automation to control multiple ESP devices. For example, a PIR sensor connected to ESP8266 can trigger lights in the doorway, or IF it is already morning, can switch on the coffee machine (which is connected to a smart plug connected to the hub).  The possibilities are endless through the integration with IoT Hub.

So I think you should mention IOT hub in your document to make a wholesome paper

**Comment by SMak06** [comment]
Hey Manju! 

Thanks a lot for the insightful suggestions. I really liked the IoT hub idea, and I agree it possesses endless potential.

However, this project was just means for me to explore what IoT feels like and unfortunately I didn't like it very much. Even though I agree the ESP I used could've contributed to majority of the problems and using the one - that you gave the link of - might solve a lot of issues, it's just not my cup of tea. 

My interests lie towards the software side of things more than hardware (as of now). But, I really appreciate your advice for turning the paper wholesome. So, if I ever do decide to publish it, I shall make appropriate amendments. 

Thanks again! :)
